#首先加载的yml配置,总控,父配置文件
spring:
  profiles:
    active: test
---
#不同的子配置文件 product
spring:
  profiles: product

---
#不同的子配置文件 test
spring:
  profiles: test
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 2000ms

---
#不同的子配置文件 dev
spring:
     profiles: dev